export const movieConstants = {
    GET_POPULAR_MOVIE: 'GET_POPULAR_MOVIE',
    GET_RATED_MOVIE: 'GET_RATED_MOVIE',
    GET_UPCOMING_MOVIE: 'GET_UPCOMING_MOVIE',
    GET_ONCE_POPULAR_MOVIE: 'GET_ONCE_POPULAR_MOVIE'
}